config/routes.rb
DrDoo::Application.routes.draw do

  devise_for :views

  devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions'} 

  resources :forms

  

  resources :complete_forms, only: [:show, :edit, :update]
  resources :notifications, only: [:create, :destroy]
  get 'complete_forms/:id/:user_id' => 'complete_forms#show', as: 'view_completed_form'
  authenticated :user do
    root to: 'forms#index'
  end

  root to: 'homes#index'

end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    if current_user
      @user = current_user
      @request_notifications = Notification.where(recipient_email: @user.email, completed: false)
      @send_notifications = Notification.where(sender_id: @user.id, completed: false)
      @completed_notifications = Notification.where(sender_id: @user.id, completed: true)
      @form = @user.forms.find_or_create_by_title('User Contact Info')
      @form_answer = @user.contact_form(@form)
    else
      redirect_to root_path
    end
  end

  def show
    @form = Form.find(params[:id])
  end

  def new
    @form_elements = Element.all
    @field = Field.new
    @forms = Form.new
  end

  def create
    if params[:fields]
      @form = current_user.forms.create(params[:form])
      params[:fields].each do |field|
        element = Element.find(field[:element_id])
        @form.fields.create(element_id: element.id, label: element.label)
      end
      redirect_to form_path(@form)
    else
      redirect_to new_form_path
    end 
  end

  def update
    @form = Form.find(params[:id])
    @form.update_attributes(title: params[:form][:title])
    @form.fields.destroy_all
    params[:fields].each do |field|
      element = Element.find(field[:element_id])
      @form.fields.create(element_id: element.id, label: element.label)
    end 
    redirect_to form_path(@form)
  end

  def destroy
    @form = Form.find(params[:id])
    @form.destroy
    redirect_to forms_path
  end

  def edit
    @form = Form.find(params[:id])
    @form_elements = Element.all
    @field = Field.new
  end
end

app/views/forms/_email_form.html.erb
<div id='emailModal' style='display: none' class="modal hide fade">
  <div class="modal-header">
    <h2 class="modal-h2">Send Form Request Email</h2>
  </div>
  <div class="modal-body">
    <h5 id="errors" class="error">&nbsp;</h5>
    <%= form_tag(notifications_path, remote: true, id: 'email_form', 'data-type' => :json) do %>
      <input type="hidden" name="form_id" />
      <div>
        <%= label_tag :email, 'Type Email of Person to Send Form Request'%><br />
        <%= email_field_tag :email, nil, :autofocus => true, class: 'span5' %>
      </div>
      <div class="modal-footer">
        <button class="btn btn-block btn-inverse" type="submit" id='email_submit'>Send Email</button>
      </div>
    <% end %>
  </div>
</div>

app/views/forms/edit.html.erb
<h1>Edit Your Form here!</h1>

<div class='form_block well'>
  <%= form_tag(form_path(@form), method: :put, class: 'form_field_catcher' )%>
  <%= submit_tag 'Submit Form →', class: 'btn btn-primary btn-large create_form_submit' %><br><br>
  <div class='title_tag'>
    <%=  label_tag 'form', 'Title', class: 'span3' %><br>
    <%= text_field_tag 'form[title]', @form.title, placeholder: 'Enter New Form Title Here' %>
  </div>
  <% @form.fields.each do |field| %>
    <div class='ui-draggable added' style='position:relative;'>
      <%= label_tag field.label, nil, class: field.element.size %><br>
      <%= text_field_tag nil, nil, placeholder: field.label.humanize, class: field.element.size %>
      <%= hidden_field_tag 'fields[][element_id]', field.element.id %>
    </div>
  <% end %>
</div>  

<div class='form_block selectables'>
  <% if @form_elements %>
    <% @form_elements.each do |element| %>
      <div class='field_type'>
        <%= label_tag element.label, nil, class: element.size %><br>
        <%= text_field_tag nil, nil, placeholder: element.label.humanize, class: element.size %>
        <%= hidden_field_tag 'fields[][element_id]', element.id %>
      </div>
    <% end %>
  <% end %>
</div>
 

app/views/forms/index.html.erb
<div id='profile'>    
  <h1>&nbsp;Welcome <%=@user.name %>! <small><br>&nbsp; Manage your forms --></small></h1>
</div>

<div class='top_level'>
  <div class="notifications">
    <% if @request_notifications.empty? && @send_notifications.empty? && @completed_notifications.empty? %>
       <h4 class="heading">You have no new notifications.</h4>
    <% else %>
      <h4 class="heading">You have new notifications!</h4>
    <% end %>

    <% if !@request_notifications.empty? %>
      <% @request_notifications.each do |notify| %>
        <h6 class="heading"><%=User.find(notify.sender_id).name %> Has set you the <%=Form.find(notify.form_id).title %> form to complete!<br/><%= link_to 'Complete This Form', complete_form_path(Form.find(notify.form_id), data: {form_id: notify.form.id, user_id: @current_user.id}) %></h6><br/>
      <% end %>
    <% end %>

    <% if !@send_notifications.empty? %>
      <% @send_notifications.each do |notify| %>
        <h6 class="heading">You have sent a request to complete your <span class='form_title'><%=Form.find(notify.form_id).title %></span> form to <span class='email_notify'><%=notify.recipient_email %></span>.</h6><br/>
      <% end %>
    <% end %>

    <% if !@completed_notifications.empty? %>
      <% @completed_notifications.each do |notify| %>
      <div id='<%=notify.id%>'>
      <h6 class="heading"><span class='form_title'><%=Form.find(notify.form_id).title %></span> has been completed by <span class='email_notify'><%=notify.recipient_email %></span>.</h6><%= link_to 'Delete', notification_path(notify), :method => :delete, remote: true, class: 'delete_link' %>
        <%= link_to 'View', view_completed_form_path(notify.form_id, User.find_by_email(notify.recipient_email).id), :method => :get, class: 'view_link' %><br/>
      </div>
      <% end %>
    <% end %>
  </div>

  <div class = 'user_info'>
    <h3><%= @form_answer.form.title %></h3>
    <% @form_answer.value.each do |value| %>
      <p><b><%= value[0].humanize %>: </b> <%= value[1] %></p><br>
    <% end %>
  </div>
</div>

<div class='user_forms'>

  <h4>Forms I've Taken</h4>
  <hr class='hr_line'/>
  <% @user.answers.each do |answer| %>
    <div class='list_forms'>
      <h6><%= answer.form.title %></h6> 
      <%= link_to 'Edit', edit_complete_form_path(answer.form.id) %>
    </div>
  <% end %>
  <br>
  <h4>Forms I created</h4>
  <hr class='hr_line'/>
  <% @user.forms.each do |form| %>
    <div class='list_forms'>
      <h6><%= form.title %></h6>
      <%= link_to 'Delete', form_path(form), :method => :delete, :confirm => 'Are you Sure?', class: 'delete_link'  %>
       <%= link_to 'Edit', edit_form_path(form) %>
       <%= link_to 'View', form_path(form) %>
       <%= link_to 'Send', '#emailModal', class: 'send_link', 'data-form' => form.id  %>
    </div>
  <% end %>
  <br>
</div>

<%= render partial: "email_form" %>

app/views/forms/new.html.erb
<div class='form_block well'>
  <%= form_tag('/forms', method: :post, class: 'form_field_catcher' )%>
    <%= submit_tag 'Submit Form →', class: 'btn btn-primary btn-large create_form_submit' %><br><br>
      <div class='title_tag'>
        <%=  label_tag 'form', 'Title', class: 'span3' %><br>
      <%= text_field_tag 'form[title]', nil, placeholder: 'Enter New Form Title Here', required: true %>
    </div><br>
</div>  

<div class='form_block selectables'>
  <% if @form_elements %>
    <% @form_elements.each do |element| %>
      <div class='field_type'>
        <%= label_tag element.label, nil, class: element.size %><br>
        <%= text_field_tag nil, nil, placeholder: element.label.humanize, class: element.size %>
        <%= hidden_field_tag 'fields[][element_id]', element.id %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/forms/show.html.erb
<div class='form_block well'>
  <%= form_for @form do |f| %>
    <h3><%= @form.title %></h3> 
    <% @form.fields.each do |field| %>
      <div class='show_field'>
        <%= label_tag field.label, nil, class: field.element.size %><br>
        <%= text_field_tag nil, nil, placeholder: field.label.humanize, class: field.element.size %>
      </div>
    <% end %>
  <% end %>
</div>  
    