config/routes.rb
DrDoo::Application.routes.draw do

  devise_for :views

  devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions'} 

  resources :forms

  

  resources :complete_forms, only: [:show, :edit, :update]
  resources :notifications, only: [:create, :destroy]
  get 'complete_forms/:id/:user_id' => 'complete_forms#show', as: 'view_completed_form'
  authenticated :user do
    root to: 'forms#index'
  end

  root to: 'homes#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <title>doolittle</title>
  <head>
    <title>DrDoo</title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <div class="navbar">
      <div class="navbar-inner">
        <%= link_to "doolittle", root_path, method: :get, class: "brand" %>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li><%= link_to "Create Form", new_form_path %></li>
            <li><%= link_to "Profile", forms_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li id='create_li'><%=link_to "Sign Up", '#Sign_up', data: {toggle: "modal"} %></li>
            <li id='create_li'><%=link_to "Sign In", '#Sign_in', data: {toggle: "modal"} %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <%= yield %>

    <div id="Sign_up" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
        <h3 id="myModalLabel">Sign up</h3>
      </div>

      <div class="modal-body">
        <%= form_for(resource, :as => resource_name,
                             :url => registration_path(resource_name),
                             :html => {:id => "sign_up_user"},
                             :format => :json,
                             :remote => :true) do |f| %>
          <%= devise_error_messages! %>                 
          <div><%= f.label :name %><br />
            <%= f.text_field :name %>
          </div>
          <div><%= f.label :email %><br />
            <%= f.email_field :email %>
          </div>
          <div><%= f.label :password %><br />
            <%= f.password_field :password %>
          </div>
          <div id='sign_up_password'><%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation %><br>
          </div>  
          <div class="modal-footer">
            <button type='submit' class="btn btn-primary">Sign Up</button>
          </div>
        <% end %>
      </div>
    </div>

    <div id="Sign_in" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
        <h3 id="myModalLabel">Sign In</h3>
      </div>

      <div class="modal-body">
        <%= form_for(resource, :as => resource_name, 
                             :url => session_path(resource_name),
                             :html => {:id => "sign_in_user"},
                             :format => :json,
                             :remote => :true) do |f| %>
          <div>
            <%= f.label :email %><br />
            <%= f.email_field :email, :autofocus => true %>
          </div>
          <div id='sign_in_password'><%= f.label :password %><br />
            <%= f.password_field :password %><br>
          </div>
          <%= render "devise/shared/links" %>
          <div class="modal-footer">
            <button type='submit' class="btn btn-primary">Sign In</button>
          </div>
        <% end %>
      </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>